-----------------------------SQL Advance Case Study-------------------------------------------

SELECT * FROM DIM_MANUFACTURER
SELECT * FROM DIM_MODEL
SELECT * FROM DIM_CUSTOMER
SELECT * FROM DIM_LOCATION
SELECT * FROM DIM_DATE
SELECT * FROM FACT_TRANSACTIONS

--Q1--BEGIN 


SELECT DISTINCT [State]
FROM FACT_TRANSACTIONS AS FT
JOIN DIM_CUSTOMER AS DC ON FT.IDCustomer = DC.IDCustomer
JOIN DIM_LOCATION AS DL ON FT.IDLocation = DL.IDLocation
WHERE [Date] BETWEEN '2005-01-01' AND GETDATE()
ORDER BY [State]

--Q1--END


--Q2--BEGIN


SELECT TOP 1 
STATE FROM DIM_LOCATION AS DL
INNER JOIN FACT_TRANSACTIONS AS FT ON DL.IDLocation = FT.IDLocation
INNER JOIN DIM_MODEL AS DM ON FT.IDMODEL = DM.IDMODEL
INNER JOIN DIM_MANUFACTURER AS DIMM ON DIMM.IDMANUFACTURER= DM.IDMANUFACTURER
WHERE MANUFACTURER_NAME = 'Samsung'
GROUP BY STATE
ORDER BY SUM(QUANTITY) DESC

--Q2--END

--Q3--BEGIN 

	
SELECT MODEL_NAME, ZIPCODE, STATE, COUNT(IDCUSTOMER) AS NO_OF_TRANSACTIONS
FROM DIM_LOCATION AS DL
INNER JOIN FACT_TRANSACTIONS AS FT ON DL.IDLocation = FT.IDLOCATION
INNER JOIN DIM_MODEL AS DM ON FT.IDMODEL = DM.IDMODEL
GROUP BY MODEL_NAME, ZIPCODE, STATE

--Q3--END

--Q4--BEGIN


SELECT TOP 1 MODEL_NAME , Unit_price
FROM DIM_MODEL
ORDER BY UNIT_PRICE

--Q4--END

--Q5--BEGIN


SELECT MODEL_NAME, AVG(UNIT_PRICE) AS AVG_PRICE
FROM DIM_MODEL
INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
WHERE MANUFACTURER_NAME IN 
(
   SELECT TOP 5 MANUFACTURER_NAME FROM FACT_TRANSACTIONS 
   INNER JOIN DIM_MODEL ON FACT_TRANSACTIONS.IDMODEL = DIM_MODEL.IDMODEL
   INNER JOIN DIM_MANUFACTURER ON DIM_MANUFACTURER.IDMANUFACTURER = DIM_MODEL.IDMANUFACTURER
   GROUP BY MANUFACTURER_NAME
   ORDER BY SUM(QUANTITY)
)
GROUP BY MODEL_NAME
ORDER BY AVG(UNIT_PRICE) DESC

--Q5--END

--Q6--BEGIN


SELECT CUSTOMER_NAME, AVG(TOTALPRICE) AVG_SPENT
FROM DIM_CUSTOMER AS DC
INNER JOIN FACT_TRANSACTIONS AS FT ON DC.IDCUSTOMER = FT.IDCUSTOMER
WHERE YEAR(DATE) = 2009 
GROUP BY CUSTOMER_NAME
HAVING AVG(TOTALPRICE)>500

--Q6--END
	
--Q7--BEGIN  

	
SELECT Model_Name
FROM (
       SELECT  top 5 Model_Name, count (Quantity) AS QN
       FROM DIM_MODEL AS DM
       INNER JOIN FACT_TRANSACTIONS AS FT ON DM.IDMODEL = FT.IDModel
       
       WHERE Year(Date) IN (2008,2009,2010)
       GROUP BY Model_Name 	
       ORDER BY QN DESC
) AS X

--Q7--END	

--Q8--BEGIN


WITH RANK1 AS 
      (
        SELECT MANUFACTURER_NAME,YEAR(DATE) AS YEAR,
	    DENSE_RANK() OVER (PARTITION BY YEAR(DATE) ORDER BY SUM(TOTALPRICE) DESC) AS RANK
        FROM FACT_TRANSACTIONS AS FT
        INNER JOIN DIM_MODEL AS DM 
        ON FT.IDModel = DM.IDModel
        INNER JOIN DIM_MANUFACTURER AS DIMM
        ON DM.IDManufacturer=DIMM.IDManufacturer
        GROUP BY Manufacturer_Name ,  YEAR(DATE)
       )
SELECT YEAR, MANUFACTURER_NAME  FROM RANK1
WHERE YEAR IN ('2009','2010') AND RANK = '2'


--Q8--END

--Q9--BEGIN

	
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(DATE) = 2010 
EXCEPT 
SELECT MANUFACTURER_NAME FROM DIM_MANUFACTURER T1
INNER JOIN DIM_MODEL T2 ON T1.IDMANUFACTURER= T2.IDMANUFACTURER
INNER JOIN FACT_TRANSACTIONS T3 ON T2.IDMODEL= T3.IDMODEL
WHERE YEAR(DATE) = 2009

--Q9--END

--Q10--BEGIN

	
SELECT *, (((avg_price-pre_year)/(pre_year))*100 ) AS Nxt_year FROM 
   (
      SELECT *, LAG (avg_price ,1) OVER (PARTITION BY IDCustomer ORDER BY [year]) AS pre_year FROM (
      SELECT DC.IDCustomer , DC.Customer_Name , YEAR( FT.DATE) [year] , AVG(FT.TotalPrice)  avg_price , 
	  AVG(FT.Quantity) avg_Qty 
	  FROM  DIM_CUSTOMER AS DC
      INNER JOIN FACT_TRANSACTIONS AS FT
      ON DC.IDCustomer = FT.IDCustomer
      WHERE DC.IDCustomer IN (SELECT TOP 10 IDCustomer FROM FACT_TRANSACTIONS 
	  GROUP BY IDCustomer ORDER BY SUM(TotalPrice) DESC)
      GROUP BY  DC.IDCustomer , DC.Customer_Name , YEAR(FT.DATE)  
   ) 
       AS X) r

--Q10--END