-----------------------------------CASE STUDY RETAIL_ANALYSIS---------------------------------
SELECT * FROM Customer
SELECT * FROM prod_cat_info
SELECT * FROM Transactions

--1. What is the total number of rows in each of the 3 tables?


SELECT
(SELECT COUNT (*) FROM Customer) +
(SELECT COUNT (*) FROM prod_cat_info) +
(SELECT COUNT (*) FROM Transactions)
AS Total_Row


--2. What is the total number of transactions that have a return?


SELECT COUNT (transaction_id) AS Total_Return_Transactions
FROM Transactions


--3. As you would have noticed the dates provided across the datasets are not in a correct
-- format. as first, pls convert the date variables into valid date formats before proceeding
-- ahead.


SELECT CONVERT (varchar,dob,103) AS Formatdate
FROM Customer
SELECT CONVERT (varchar, tran_date, 103) AS Formatdate
FROM Transactions


--4. What is the time range of the transaction data available for analysis?
-- show the output in number of days, months and years simultaneously in different column.


SELECT DATEDIFF (DAY, MIN (tran_date), MAX (tran_date)) AS Days,
DATEDIFF (MONTH, MIN (tran_date), MAX (tran_date)) AS Months, 
DATEDIFF (YEAR, MIN (tran_date), MAX (tran_date)) AS Years 
FROM Transactions


--5. Which product category does the sub-category "diy"belong to?


SELECT prod_cat FROM prod_cat_info
WHERE prod_subcat = 'DIY'



--------------------------------------Data analysis-------------------------------------------

--1. Which channel is most frequently used for transactions?


SELECT TOP 1 store_type AS chennel,
COUNT (store_type) AS 'frequency'
FROM Transactions
GROUP BY store_type
ORDER BY 'frequency' Desc


--2. What is the count of Male and Female customers in the database?


SELECT GENDER, COUNT (CUSTOMER_ID) AS COUNT
FROM CUSTOMER
WHERE GENDER IN ('M' , 'F')
GROUP BY GENDER


--3. From which city do we have the maximum number of customers and how many?

SELECT TOP 1
city_code, COUNT (customer_ID) cust_cnt
FROM Customer
GROUP BY city_code
ORDER BY cust_cnt DESC



--4. How many sub-categories are there under the Books category?


SELECT COUNT (prod_subcat) AS subcat_cnt
FROM prod_cat_info
WHERE prod_cat = 'BOOKS'
GROUP BY prod_cat


--5. What is the maximum quantity of products ever ordered?


SELECT COUNT (QTY) AS MAX_QTY,PCI.PROD_CAT 
FROM TRANSACTIONS AS T
INNER JOIN PROD_CAT_INFO AS PCI
ON PCI.PROD_SUB_CAT_CODE = T.PROD_SUBCAT_CODE
GROUP BY PCI.PROD_CAT
ORDER BY MAX_QTY DESC


--6. What is the net total revenue generated in categories Electronics and Books?


SELECT SUM (TOTAL_AMT) AMOUNT
FROM Transactions AS T
INNER JOIN prod_cat_info AS PCI ON T.prod_cat_code = PCI.prod_cat_code
AND T.prod_subcat_code = PROD_SUBCAT_CODE
WHERE PROD_CAT IN ('BOOKS' , 'ELECTRONICS')


--7. How many customers have >10 transactions with us, excluding returns?


SELECT COUNT (CUSTOMER_ID) AS CUSTOMER_COUNT
FROM CUSTOMER WHERE CUSTOMER_ID IN 
(
SELECT CUST_ID
FROM Transactions
LEFT JOIN CUSTOMER ON CUSTOMER_ID = CUST_ID
WHERE TOTAL_AMT NOT LIKE '-%'
GROUP BY CUST_ID
HAVING COUNT (TRANSACTION_ID) > 10)


--8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, 
-- from “Flagship stores”?


SELECT SUM (TOTAL_AMT) AS AMOUNT FROM Transactions AS T
INNER JOIN prod_cat_info AS PCI ON T.prod_cat_code = PCI.prod_cat_code
  AND prod_subcat_code = PROD_SUBCAT_CODE 
WHERE PROD_CAT IN ('CLOTHING','ELECTRONICS')
  AND STORE_TYPE = 'FLAGSHIP STORE'


--9. What is the total revenue generated from “Male” customers in “Electronics” category?
-- Output should display total revenue by prod sub-cat.


SELECT PROD_SUBCAT, SUM (TOTAL_AMT) AS TOTAL_REVENUE 
FROM Transactions AS T
INNER JOIN prod_cat_info AS PCI ON T.prod_cat_code = PCI.prod_cat_code 
  AND T.prod_subcat_code = PCI.prod_sub_cat_code
INNER JOIN Customer AS C ON T.cust_id = C.customer_Id
WHERE prod_cat = 'Electronics' and Gender = 'M'
GROUP BY prod_subcat


--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

SELECT TOP 5 PCI.prod_subcat,
SUM (T.total_amt) AS Total_Sales,
SUM (T.Tax) AS Total_Returns,
(SUM (T.total_amt) - SUM (T.Tax)) AS Net_Sales,
(SUM (T.total_amt) - SUM (T.Tax)) / SUM (T.total_amt) * 100 AS Sales_Percentage
FROM Transactions AS T
JOIN prod_cat_info AS PCI ON T.prod_cat_code = PCI.prod_cat_code
GROUP BY PCI.prod_subcat
ORDER BY net_sales DESC


--11. For all customers aged between 25 to 35 years find what is the net total revenue
-- generated by these consumers in last 30 days of transactions from max transaction date
-- available in the data?

SELECT cust_id ,SUM (total_amt) AS Total_Revenue
FROM Transactions
WHERE cust_id in
     (
	   SELECT CUSTOMER_ID FROM Customer
	   WHERE DATEDIFF (YEAR,DOB,GETDATE()) BETWEEN 25 AND 35
	 )
AND TRAN_DATE BETWEEN DATEADD (DAY,-30,(SELECT MAX (TRAN_DATE) FROM TRANSACTIONS))
AND (SELECT MAX (TRAN_DATE) FROM Transactions)
GROUP BY CUST_ID


--12. Which product category has seen the max value of returns in the last 3 months of 
-- transactions?


SELECT TOP 1 PROD_CAT, SUM (TOTAL_AMT) AS MAX_RETURN
FROM TRANSACTIONS AS T
INNER JOIN prod_cat_info AS PCI ON T.prod_cat_code = PCI.prod_cat_code
  AND T.prod_subcat_code = PCI.prod_sub_cat_code
WHERE TOTAL_AMT < 0
  AND TRAN_DATE BETWEEN DATEADD (MONTH,-3,(SELECT MAX (TRAN_DATE) FROM TRANSACTIONS))
  AND (SELECT MAX (TRAN_DATE) FROM TRANSACTIONS)
GROUP BY PROD_CAT
ORDER BY MAX_RETURN DESC


--13. Which store-type sells the maximum products; by value of sales amount and by quantity
-- sold?


SELECT TOP 1 Store_type , SUM (total_amt) AS Sales_Amount,
SUM(CAST (Qty AS Int)) AS Qty_Sold
FROM Transactions
GROUP BY Store_type
ORDER BY Qty_Sold DESC


--14. What are the categories for which average revenue is above the overall average.


SELECT prod_cat , AVG (total_amt) AS Avg_Revenue
FROM Transactions as T
INNER JOIN prod_cat_info as PCI ON T.prod_cat_code = PCI.prod_cat_code
GROUP BY prod_cat
HAVING AVG(total_amt) > (SELECT AVG (total_amt) FROM Transactions)


--15. Find the average and total revenue by each subcategory for the categories which are 
-- among top 5 categories in terms of quantity sold.


SELECT TOP 5 prod_subcat, AVG (total_amt) AS Avg_Revenue, 
SUM (CAST (Qty AS int)) AS Net_Quantity
FROM Transactions AS T
INNER JOIN prod_cat_info AS PCI ON T.prod_cat_code = PCI.prod_cat_code
GROUP BY prod_subcat, prod_cat
ORDER BY Net_Quantity DESC
